// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: Models.proto

package rpcservices

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GameInfoInnerVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameCode          string `protobuf:"bytes,1,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	GameName          string `protobuf:"bytes,2,opt,name=gameName,proto3" json:"gameName,omitempty"`
	GroupName         string `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	MathOdds          string `protobuf:"bytes,4,opt,name=mathOdds,proto3" json:"mathOdds,omitempty"`
	BettingName       string `protobuf:"bytes,5,opt,name=bettingName,proto3" json:"bettingName,omitempty"`
	BettingId         string `protobuf:"bytes,6,opt,name=bettingId,proto3" json:"bettingId,omitempty"`
	MethodName        string `protobuf:"bytes,7,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Attributes        string `protobuf:"bytes,8,opt,name=attributes,proto3" json:"attributes,omitempty"`
	LotteryAttributes string `protobuf:"bytes,9,opt,name=lotteryAttributes,proto3" json:"lotteryAttributes,omitempty"`
	PageAttributes    string `protobuf:"bytes,10,opt,name=pageAttributes,proto3" json:"pageAttributes,omitempty"`
	Sort              string `protobuf:"bytes,11,opt,name=sort,proto3" json:"sort,omitempty"`
	BettingStatus     string `protobuf:"bytes,12,opt,name=bettingStatus,proto3" json:"bettingStatus,omitempty"`
}

func (x *GameInfoInnerVo) Reset() {
	*x = GameInfoInnerVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfoInnerVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoInnerVo) ProtoMessage() {}

func (x *GameInfoInnerVo) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoInnerVo.ProtoReflect.Descriptor instead.
func (*GameInfoInnerVo) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{0}
}

func (x *GameInfoInnerVo) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *GameInfoInnerVo) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *GameInfoInnerVo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GameInfoInnerVo) GetMathOdds() string {
	if x != nil {
		return x.MathOdds
	}
	return ""
}

func (x *GameInfoInnerVo) GetBettingName() string {
	if x != nil {
		return x.BettingName
	}
	return ""
}

func (x *GameInfoInnerVo) GetBettingId() string {
	if x != nil {
		return x.BettingId
	}
	return ""
}

func (x *GameInfoInnerVo) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *GameInfoInnerVo) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *GameInfoInnerVo) GetLotteryAttributes() string {
	if x != nil {
		return x.LotteryAttributes
	}
	return ""
}

func (x *GameInfoInnerVo) GetPageAttributes() string {
	if x != nil {
		return x.PageAttributes
	}
	return ""
}

func (x *GameInfoInnerVo) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GameInfoInnerVo) GetBettingStatus() string {
	if x != nil {
		return x.BettingStatus
	}
	return ""
}

type InnerGameInfoDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag     string `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	GameCode string `protobuf:"bytes,2,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
}

func (x *InnerGameInfoDto) Reset() {
	*x = InnerGameInfoDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerGameInfoDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerGameInfoDto) ProtoMessage() {}

func (x *InnerGameInfoDto) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerGameInfoDto.ProtoReflect.Descriptor instead.
func (*InnerGameInfoDto) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{1}
}

func (x *InnerGameInfoDto) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *InnerGameInfoDto) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

type BettingMathOddsVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BettingId  string `protobuf:"bytes,1,opt,name=bettingId,proto3" json:"bettingId,omitempty"`
	MathOdds   string `protobuf:"bytes,2,opt,name=mathOdds,proto3" json:"mathOdds,omitempty"`
	Attributes string `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *BettingMathOddsVo) Reset() {
	*x = BettingMathOddsVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BettingMathOddsVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingMathOddsVo) ProtoMessage() {}

func (x *BettingMathOddsVo) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingMathOddsVo.ProtoReflect.Descriptor instead.
func (*BettingMathOddsVo) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{2}
}

func (x *BettingMathOddsVo) GetBettingId() string {
	if x != nil {
		return x.BettingId
	}
	return ""
}

func (x *BettingMathOddsVo) GetMathOdds() string {
	if x != nil {
		return x.MathOdds
	}
	return ""
}

func (x *BettingMathOddsVo) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

type BettingVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BettingId     string `protobuf:"bytes,1,opt,name=bettingId,proto3" json:"bettingId,omitempty"`
	MathOdds      string `protobuf:"bytes,2,opt,name=mathOdds,proto3" json:"mathOdds,omitempty"`
	Attributes    string `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	BettingStatus string `protobuf:"bytes,4,opt,name=bettingStatus,proto3" json:"bettingStatus,omitempty"`
	ItemsId       string `protobuf:"bytes,5,opt,name=itemsId,proto3" json:"itemsId,omitempty"`
	GroupName     string `protobuf:"bytes,6,opt,name=groupName,proto3" json:"groupName,omitempty"`
}

func (x *BettingVo) Reset() {
	*x = BettingVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BettingVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingVo) ProtoMessage() {}

func (x *BettingVo) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingVo.ProtoReflect.Descriptor instead.
func (*BettingVo) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{3}
}

func (x *BettingVo) GetBettingId() string {
	if x != nil {
		return x.BettingId
	}
	return ""
}

func (x *BettingVo) GetMathOdds() string {
	if x != nil {
		return x.MathOdds
	}
	return ""
}

func (x *BettingVo) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *BettingVo) GetBettingStatus() string {
	if x != nil {
		return x.BettingStatus
	}
	return ""
}

func (x *BettingVo) GetItemsId() string {
	if x != nil {
		return x.ItemsId
	}
	return ""
}

func (x *BettingVo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type SpecialBettingVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes string `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	BettingId  string `protobuf:"bytes,2,opt,name=bettingId,proto3" json:"bettingId,omitempty"`
}

func (x *SpecialBettingVo) Reset() {
	*x = SpecialBettingVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecialBettingVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialBettingVo) ProtoMessage() {}

func (x *SpecialBettingVo) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialBettingVo.ProtoReflect.Descriptor instead.
func (*SpecialBettingVo) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{4}
}

func (x *SpecialBettingVo) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *SpecialBettingVo) GetBettingId() string {
	if x != nil {
		return x.BettingId
	}
	return ""
}

type MarkSixDataVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"` //类似于Java中的 List<String>
}

func (x *MarkSixDataVo) Reset() {
	*x = MarkSixDataVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkSixDataVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkSixDataVo) ProtoMessage() {}

func (x *MarkSixDataVo) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkSixDataVo.ProtoReflect.Descriptor instead.
func (*MarkSixDataVo) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{5}
}

func (x *MarkSixDataVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarkSixDataVo) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_Models_proto protoreflect.FileDescriptor

var file_Models_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x03, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x56, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x68, 0x4f, 0x64, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x68, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x6c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x61, 0x67,
	0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x70, 0x61, 0x67, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42, 0x0a, 0x10, 0x49,
	0x6e, 0x6e, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x74, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x6d, 0x0a, 0x11, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x68, 0x4f, 0x64,
	0x64, 0x73, 0x56, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x68, 0x4f, 0x64, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x68, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0xc3,
	0x01, 0x0a, 0x09, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61,
	0x74, 0x68, 0x4f, 0x64, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61,
	0x74, 0x68, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x42,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0d, 0x4d, 0x61, 0x72, 0x6b, 0x53, 0x69,
	0x78, 0x44, 0x61, 0x74, 0x61, 0x56, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Models_proto_rawDescOnce sync.Once
	file_Models_proto_rawDescData = file_Models_proto_rawDesc
)

func file_Models_proto_rawDescGZIP() []byte {
	file_Models_proto_rawDescOnce.Do(func() {
		file_Models_proto_rawDescData = protoimpl.X.CompressGZIP(file_Models_proto_rawDescData)
	})
	return file_Models_proto_rawDescData
}

var file_Models_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Models_proto_goTypes = []interface{}{
	(*GameInfoInnerVo)(nil),   // 0: proto.GameInfoInnerVo
	(*InnerGameInfoDto)(nil),  // 1: proto.InnerGameInfoDto
	(*BettingMathOddsVo)(nil), // 2: proto.BettingMathOddsVo
	(*BettingVo)(nil),         // 3: proto.BettingVo
	(*SpecialBettingVo)(nil),  // 4: proto.SpecialBettingVo
	(*MarkSixDataVo)(nil),     // 5: proto.MarkSixDataVo
}
var file_Models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Models_proto_init() }
func file_Models_proto_init() {
	if File_Models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfoInnerVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerGameInfoDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BettingMathOddsVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BettingVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecialBettingVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkSixDataVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Models_proto_goTypes,
		DependencyIndexes: file_Models_proto_depIdxs,
		MessageInfos:      file_Models_proto_msgTypes,
	}.Build()
	File_Models_proto = out.File
	file_Models_proto_rawDesc = nil
	file_Models_proto_goTypes = nil
	file_Models_proto_depIdxs = nil
}
